import Head from 'next/head';

import { Layout } from "../components/Layout";
import { NavBar } from '../components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Menu Sprite</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <NavBar />
      </Layout>
    </>
  )
}
