import Head from 'next/head';

import { Layout } from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Menu Sprite</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout />
    </>
  )
}
