import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Menu Sprite</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      
    </>
  )
}
